# Numpy

In [2]:
# np array
import numpy as np

a = np.array([1,2,3])
print(type(a)) # python data type
print(a.dtype) # numpy data type
print(a.shape) # shape of the array
print(a.ndim) # number of dimensions
print(a.size) # number of elements in the array
print(a.itemsize) # size of each element in bytes

<class 'numpy.ndarray'>
int64
(3,)
1
3
8


In [29]:
# creating a np array

# from a list
a = np.array([1, 2, 3])
print(a)

# using arange
a = np.arange(10)  # creates an array with values from 0 to 9
print(a)

# using linspace
a = np.linspace(0, 1, 5)  # creates an array with 5 values evenly spaced between 0 and 1
print(a)

# zeros and ones
a = np.zeros(4)  # creates a 2x3 array filled with zeros
print(a)
b = np.ones((2, 3))  # creates a 2x3 array filled with ones
print(b)

# identity matrix
a = np.identity(3)  # creates a 3x3 identity matrix
print(a)

# from np.random
a = np.random.rand(3,2)  # creates a 3x2 array with random values between 0 and 1
print(a)



[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.49697535 0.66200653]
 [0.22720326 0.87250175]
 [0.7489501  0.04233577]]


In [37]:
# using new generator api for generaimg random numbers
rng = np.random.default_rng()

a = rng.random((3, 2))  # creates a 3x2 array with random values between 0 and 1
print(a)

a = rng.standard_normal((3, 2))  # creates a 3x2 array with random values from a standard normal distribution
print(a)

a = rng.integers(0, 10, size=(3, 2))  # creates a 3x2 array with random integers between 0 and 10
print(a)


[[0.6302602  0.04056833]
 [0.03770141 0.17545154]
 [0.59824139 0.98953108]]
[[ 1.52842957  1.79495452]
 [-1.18230744 -0.03938822]
 [ 1.25627356 -0.27738854]]
[[5 3]
 [6 6]
 [3 3]]


In [12]:
# numpy strides
a = np.array([[1,2,3], [9, 8,7], [4,5,3], [10,11,15]])
print(a.strides)
a.dtype


(24, 8)


dtype('int64')

In [ ]:
# creating array using np.fromfunction
def func(i,j):
    return i + j

a = np.fromfunction(func, (4, 3), dtype=int) 
print(a)

[[0 0 0]
 [2 2 2]
 [4 4 4]
 [6 6 6]]
