# Numpy

In [9]:
# np array
import numpy as np

a = np.array([1,2,3])
print(type(a)) # python data type
print(a.dtype) # numpy data type
print(a.shape) # shape of the array
print(a.ndim) # number of dimensions
print(a.size) # number of elements in the array
print(a.itemsize) # size of each element in bytes

<class 'numpy.ndarray'>
int64
(3,)
1
3
8


In [29]:
# creating a np array

# from a list
a = np.array([1, 2, 3])
print(a)

# using arange
a = np.arange(10)  # creates an array with values from 0 to 9
print(a)

# using linspace
a = np.linspace(0, 1, 5)  # creates an array with 5 values evenly spaced between 0 and 1
print(a)

# zeros and ones
a = np.zeros(4)  # creates a 2x3 array filled with zeros
print(a)
b = np.ones((2, 3))  # creates a 2x3 array filled with ones
print(b)

# identity matrix
a = np.identity(3)  # creates a 3x3 identity matrix
print(a)

# from np.random
a = np.random.rand(3,2)  # creates a 3x2 array with random values between 0 and 1
print(a)



[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.49697535 0.66200653]
 [0.22720326 0.87250175]
 [0.7489501  0.04233577]]
